version: '3.1'

services:

  db:
    image: postgres:latest
    ports:
    - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
     - ./db_data:/var/lib/postgresql/data