version: '3.1'

services:

  db:
    image: postgres:latest
    ports:
    - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
     - ./db_data:/var/lib/postgresql/data

  dbviewer2:
     image: dpage/pgadmin4:latest
     ports:
      - 8080:80
     environment:
      PGADMIN_DEFAULT_EMAIL: pavel@hw4.com
      PGADMIN_DEFAULT_PASSWORD: root
     depends_on:
      - db